import Head from "next/head";
import Header from "../../components/Header";
import Nav from "../../components/Nav";

function Details() {
  const containerStyles = `
  3xl:ml-auto
  3xl:mr-auto
  3xl:max-w-screen-3xl
`;
  return (
    <div className={containerStyles}>
      <Head>
        <title>Hulu Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <div></div>
    </div>
  );
}

export default Details;
