import Head from "next/head";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Gallery from "../components/Gallery";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Hulu Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header />

      {/* Nav */}
      <Nav />

      {/* Gallery */}
      <Gallery />
    </div>
  );
}
